apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-deployment
  namespace: http
spec:
  selector:
    matchLabels:
      app: http
  replicas: 1
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
      - name: http
        image: httpd:latest 
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: http
  namespace: http
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: http
