apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-deployment
  namespace: http
spec:
  selector:
    matchLabels:
      app: http
  replicas: 2
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
      - name: http
        image: httpd:latest 
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
          requests:
            memory: "50Mi"
            cpu: "50m"

---
apiVersion: v1
kind: Service
metadata:
  name: http
  namespace: http
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: http
