apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: http-hpa
  namespace: http
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: http-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
